#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage:
  validate-commit-message.sh --range <range>
  validate-commit-message.sh --root <commit>
  validate-commit-message.sh <commit> [<commit> ...]

The commit body is optional. Merge commits are skipped because their subjects
are generated by Git hosting tools rather than being changeset messages.
EOF
  exit 2
}

commits=()
while (($# > 0)); do
  case "$1" in
    --range)
      (($# >= 2)) || usage
      mapfile -t range_commits < <(git rev-list --no-merges "$2")
      commits+=("${range_commits[@]}")
      shift 2
      ;;
    --root)
      (($# >= 2)) || usage
      mapfile -t root_commits < <(git rev-list --no-merges "$2")
      commits+=("${root_commits[@]}")
      shift 2
      ;;
    --help|-h)
      usage
      ;;
    --*)
      echo "Unknown option: $1" >&2
      usage
      ;;
    *)
      commits+=("$1")
      shift
      ;;
  esac
done

((${#commits[@]} > 0)) || usage

status=0
for commit in "${commits[@]}"; do
  subject="$(git show -s --format=%s "$commit")"

  # Conventional Commits: type(scope)!: description. The body is deliberately
  # not checked here because it is documented as recommended, not mandatory.
  if [[ ! "$subject" =~ ^[a-z][a-z0-9-]*(\([[:alnum:]._/-]+\))?\!?\:[[:space:]]+[^[:space:]].*$ ]]; then
    echo "Invalid Conventional Commit message for ${commit}:" >&2
    echo "  ${subject}" >&2
    echo "Expected: type(scope)!: description" >&2
    status=1
  fi
done

exit "$status"
