# SPDX-FileCopyrightText: 2026 Amalgam Solucoes em TI Ltda.
# SPDX-License-Identifier: MIT
#

include(FindPackageHandleStandardArgs)
include("${CMAKE_CURRENT_LIST_DIR}/SkiaLinkDependencies.cmake")

get_filename_component(SKIA_DEPENDENCY_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(SKIA_LOCAL_ROOT "${SKIA_DEPENDENCY_DIR}/local")

if(NOT DEFINED SKIA_REQUIRE_BUILD_CONFIG)
  set(SKIA_REQUIRE_BUILD_CONFIG_DEFAULT OFF)
  set(SKIA_ARTIFACT_MANIFEST "${SKIA_DEPENDENCY_DIR}/artifacts.json")
  if(EXISTS "${SKIA_ARTIFACT_MANIFEST}")
    file(READ "${SKIA_ARTIFACT_MANIFEST}" SKIA_ARTIFACT_MANIFEST_CONTENT)
    string(REGEX MATCH
      "\"machine_build_config\"[^}]*\"required\"[ \t\r\n]*:[ \t\r\n]*true"
      SKIA_MANAGED_CONFIG_REQUIRED_MATCH
      "${SKIA_ARTIFACT_MANIFEST_CONTENT}"
    )
    if(SKIA_MANAGED_CONFIG_REQUIRED_MATCH)
      set(SKIA_REQUIRE_BUILD_CONFIG_DEFAULT ON)
    endif()
  endif()
  set(SKIA_REQUIRE_BUILD_CONFIG "${SKIA_REQUIRE_BUILD_CONFIG_DEFAULT}" CACHE BOOL
    "Require machine metadata for repository-managed Skia prebuilts"
  )
endif()

if(NOT DEFINED SKIA_DIR)
  set(SKIA_DIR "${SKIA_LOCAL_ROOT}" CACHE PATH "Skia prebuilt directory")
endif()

if(DEFINED ANDROID_ABI)
  set(SKIA_PLATFORM "android")
  set(SKIA_ARCH "${ANDROID_ABI}")
elseif(APPLE AND (CMAKE_SYSTEM_NAME STREQUAL "iOS" OR CMAKE_OSX_SYSROOT MATCHES "[Ii][Pp]hone"))
  if(CMAKE_OSX_SYSROOT MATCHES "[Ii][Pp]hone[Ss]imulator")
    set(SKIA_PLATFORM "ios-simulator")
  else()
    set(SKIA_PLATFORM "ios")
  endif()
  set(SKIA_ARCH "${CMAKE_OSX_ARCHITECTURES}")
  if(SKIA_ARCH)
    list(LENGTH SKIA_ARCH SKIA_ARCH_LEN)
    if(SKIA_ARCH_LEN GREATER 1)
      message(FATAL_ERROR "Skia expects a single iOS architecture, got: ${SKIA_ARCH}")
    endif()
    list(GET SKIA_ARCH 0 SKIA_ARCH)
  else()
    set(SKIA_ARCH "arm64")
  endif()
  if(SKIA_ARCH STREQUAL "aarch64")
    set(SKIA_ARCH "arm64")
  endif()
elseif(WIN32)
  set(SKIA_PLATFORM "windows")
  set(SKIA_WINDOWS_PLATFORM "${CMAKE_VS_PLATFORM_NAME}")
  if(NOT SKIA_WINDOWS_PLATFORM)
    set(SKIA_WINDOWS_PLATFORM "${CMAKE_GENERATOR_PLATFORM}")
  endif()
  string(TOLOWER "${SKIA_WINDOWS_PLATFORM}" SKIA_WINDOWS_PLATFORM_LOWER)
  if(SKIA_WINDOWS_PLATFORM_LOWER STREQUAL "win32")
    set(SKIA_ARCH "x86")
  elseif(SKIA_WINDOWS_PLATFORM_LOWER STREQUAL "x64")
    set(SKIA_ARCH "x64")
  elseif(SKIA_WINDOWS_PLATFORM_LOWER STREQUAL "arm64")
    set(SKIA_ARCH "arm64")
  elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(SKIA_ARCH "x64")
  else()
    set(SKIA_ARCH "x86")
  endif()
elseif(APPLE)
  set(SKIA_PLATFORM "macos")
  set(SKIA_ARCH "${CMAKE_OSX_ARCHITECTURES}")
  if(SKIA_ARCH)
    list(LENGTH SKIA_ARCH SKIA_ARCH_LEN)
    if(SKIA_ARCH_LEN GREATER 1)
      message(FATAL_ERROR "Skia expects a single macOS architecture, got: ${SKIA_ARCH}")
    endif()
    list(GET SKIA_ARCH 0 SKIA_ARCH)
  else()
    set(SKIA_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
  endif()
  if(SKIA_ARCH STREQUAL "amd64")
    set(SKIA_ARCH "x86_64")
  elseif(SKIA_ARCH STREQUAL "aarch64")
    set(SKIA_ARCH "arm64")
  endif()
elseif(CMAKE_SYSTEM_NAME STREQUAL "Emscripten")
  set(SKIA_PLATFORM "wasm")
  set(SKIA_ARCH "wasm32")
elseif(UNIX AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(SKIA_PLATFORM "linux")
  set(SKIA_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
  if(SKIA_ARCH STREQUAL "amd64")
    set(SKIA_ARCH "x86_64")
  elseif(SKIA_ARCH STREQUAL "arm64")
    set(SKIA_ARCH "aarch64")
  elseif(SKIA_ARCH STREQUAL "arm" OR SKIA_ARCH STREQUAL "armv7")
    set(SKIA_ARCH "armv7l")
  endif()
endif()

if(NOT SKIA_PLATFORM OR NOT SKIA_ARCH)
  message(FATAL_ERROR "Unsupported Skia platform '${CMAKE_SYSTEM_NAME}' / '${CMAKE_SYSTEM_PROCESSOR}'")
endif()

set(SKIA_LIBRARY_DIRS "${SKIA_DIR}/out/Release/${SKIA_PLATFORM}/${SKIA_ARCH}" CACHE PATH "Skia library directory" FORCE)

set(SKIA_EXPLICIT_EXTERNAL_LIBRARY OFF)
if(DEFINED SKIA_LIBRARY AND EXISTS "${SKIA_LIBRARY}")
  get_filename_component(SKIA_EXPLICIT_LIBRARY_ABSOLUTE "${SKIA_LIBRARY}" ABSOLUTE)
  string(FIND "${SKIA_EXPLICIT_LIBRARY_ABSOLUTE}" "${SKIA_LOCAL_ROOT}/" SKIA_EXPLICIT_LIBRARY_LOCAL_INDEX)
  if(NOT SKIA_EXPLICIT_LIBRARY_LOCAL_INDEX EQUAL 0)
    set(SKIA_EXPLICIT_EXTERNAL_LIBRARY ON)
  endif()
endif()

set(SKIA_LIBPNG_MODULE_DIR "${SKIA_DEPENDENCY_DIR}/../libpng/cmake")
set(SKIA_ZLIB_MODULE_DIR "${SKIA_DEPENDENCY_DIR}/../zlib-ng/cmake")
if(EXISTS "${SKIA_LIBPNG_MODULE_DIR}/FindPNG.cmake")
  list(APPEND CMAKE_MODULE_PATH "${SKIA_LIBPNG_MODULE_DIR}")
endif()
if(EXISTS "${SKIA_ZLIB_MODULE_DIR}/FindZLIB.cmake")
  list(APPEND CMAKE_MODULE_PATH "${SKIA_ZLIB_MODULE_DIR}")
endif()

foreach(SKIA_CACHED_VAR
    SKIA_CONFIG_INCLUDE_DIR
    SKIA_CORE_INCLUDE_DIR
    SKIA_UTILS_INCLUDE_DIR
    SKIA_EFFECTS_INCLUDE_DIR
    SKIA_GPU_INCLUDE_DIR
    SKIA_GPU2_INCLUDE_DIR
    SKIA_LIBRARY
    SKIA_LIBRARY_DIRS
    SKIA_LIBRARIES)
  if(DEFINED ${SKIA_CACHED_VAR})
    if(SKIA_CACHED_VAR STREQUAL "SKIA_LIBRARY" AND SKIA_EXPLICIT_EXTERNAL_LIBRARY)
      continue()
    endif()
    string(FIND "${${SKIA_CACHED_VAR}}" "${SKIA_DIR}" SKIA_CACHED_VAR_DEPOT_INDEX)
    if("${${SKIA_CACHED_VAR}}" MATCHES "-NOTFOUND$" OR NOT SKIA_CACHED_VAR_DEPOT_INDEX EQUAL 0)
      unset(${SKIA_CACHED_VAR} CACHE)
      unset(${SKIA_CACHED_VAR})
    endif()
  endif()
endforeach()

find_path(
  SKIA_CONFIG_INCLUDE_DIR
  SkUserConfig.h
  HINTS "${SKIA_DIR}/include/config"
  NO_DEFAULT_PATH
  NO_CMAKE_FIND_ROOT_PATH
  )
find_path(
  SKIA_CORE_INCLUDE_DIR
  SkCanvas.h
  HINTS "${SKIA_DIR}/include/core"
  NO_DEFAULT_PATH
  NO_CMAKE_FIND_ROOT_PATH
  )
find_path(
  SKIA_UTILS_INCLUDE_DIR
  SkRandom.h
  HINTS "${SKIA_DIR}/include/utils"
  NO_DEFAULT_PATH
  NO_CMAKE_FIND_ROOT_PATH
  )
find_path(
  SKIA_EFFECTS_INCLUDE_DIR
  SkImageSource.h
  HINTS "${SKIA_DIR}/include/effects"
  NO_DEFAULT_PATH
  NO_CMAKE_FIND_ROOT_PATH
  )
find_path(
  SKIA_GPU_INCLUDE_DIR
  GrContext.h
  HINTS "${SKIA_DIR}/include/gpu"
  NO_DEFAULT_PATH
  NO_CMAKE_FIND_ROOT_PATH
  )
find_path(
  SKIA_GPU2_INCLUDE_DIR
  gl/GrGLDefines.h
  HINTS "${SKIA_DIR}/src/gpu"
  NO_DEFAULT_PATH
  NO_CMAKE_FIND_ROOT_PATH
  )

set(SKIA_INCLUDE_DIRS "${SKIA_DIR}")
foreach(SKIA_INCLUDE_CANDIDATE
    SKIA_CONFIG_INCLUDE_DIR
    SKIA_CORE_INCLUDE_DIR
    SKIA_UTILS_INCLUDE_DIR
    SKIA_EFFECTS_INCLUDE_DIR
    SKIA_GPU_INCLUDE_DIR
    SKIA_GPU2_INCLUDE_DIR)
  if(DEFINED ${SKIA_INCLUDE_CANDIDATE} AND EXISTS "${${SKIA_INCLUDE_CANDIDATE}}")
    list(APPEND SKIA_INCLUDE_DIRS "${${SKIA_INCLUDE_CANDIDATE}}")
  endif()
endforeach()
list(REMOVE_DUPLICATES SKIA_INCLUDE_DIRS)

if(WIN32)
  find_library(SKIA_LIBRARY
    NAMES libskia skia
    HINTS "${SKIA_LIBRARY_DIRS}"
    NO_DEFAULT_PATH
    NO_CMAKE_FIND_ROOT_PATH
  )
else()
  find_library(SKIA_LIBRARY
    NAMES skia libskia
    HINTS "${SKIA_LIBRARY_DIRS}"
    NO_DEFAULT_PATH
    NO_CMAKE_FIND_ROOT_PATH
  )
endif()

set(SKIA_LIBRARIES "${SKIA_LIBRARY}" CACHE PATH "Skia library" FORCE)
if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND SKIA_LIBRARY)
  set(SKIA_LIBRARIES -Wl,--start-group "${SKIA_LIBRARY}" -Wl,--end-group CACHE STRING "Skia libraries" FORCE)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Skia
  REQUIRED_VARS
    SKIA_LIBRARY
    SKIA_CONFIG_INCLUDE_DIR
    SKIA_CORE_INCLUDE_DIR
    SKIA_GPU2_INCLUDE_DIR
)

if(Skia_FOUND AND NOT TARGET Skia::Skia)
  set(SKIA_INTERFACE_LIBRARIES "")
  set(SKIA_INTERFACE_COMPILE_DEFINITIONS "")
  set(SKIA_METADATA_DRIVEN OFF)
  set(SKIA_MANAGED_LIBRARY OFF)

  get_filename_component(SKIA_LIBRARY_ABSOLUTE "${SKIA_LIBRARY}" ABSOLUTE)
  string(FIND "${SKIA_LIBRARY_ABSOLUTE}" "${SKIA_LOCAL_ROOT}/" SKIA_LIBRARY_LOCAL_INDEX)
  if(SKIA_LIBRARY_LOCAL_INDEX EQUAL 0)
    set(SKIA_MANAGED_LIBRARY ON)
  endif()

  if(DEFINED SKIA_BUILD_CONFIG AND NOT SKIA_BUILD_CONFIG STREQUAL "")
    set(SKIA_SELECTED_BUILD_CONFIG "${SKIA_BUILD_CONFIG}")
  else()
    get_filename_component(SKIA_LIBRARY_DIRECTORY "${SKIA_LIBRARY_ABSOLUTE}" DIRECTORY)
    set(SKIA_SELECTED_BUILD_CONFIG "${SKIA_LIBRARY_DIRECTORY}/SkiaBuildConfig.cmake")
  endif()

  if(EXISTS "${SKIA_SELECTED_BUILD_CONFIG}")
    foreach(SKIA_BUILD_FIELD
        SKIA_BUILD_CONFIG_VERSION
        SKIA_BUILD_UPSTREAM_REVISION
        SKIA_BUILD_PLATFORM
        SKIA_BUILD_ARCHITECTURE
        SKIA_BUILD_LIBRARY_SHA256
        SKIA_BUILD_ENABLE_GPU
        SKIA_BUILD_USE_GL
        SKIA_BUILD_USE_EGL
        SKIA_BUILD_USE_METAL
        SKIA_BUILD_USE_VULKAN
        SKIA_BUILD_USE_OPENCL
        SKIA_BUILD_USE_WEBGL
        SKIA_BUILD_USE_ANGLE
        SKIA_BUILD_USE_DAWN
        SKIA_BUILD_USE_DIRECT3D
        SKIA_BUILD_USE_VMA
        SKIA_BUILD_USE_X11
        SKIA_BUILD_USE_FONTHOST_MAC
        SKIA_BUILD_USE_FREETYPE
        SKIA_BUILD_USE_SYSTEM_FREETYPE2
        SKIA_BUILD_USE_FONTCONFIG
        SKIA_BUILD_ENABLE_FONTMGR_FONTCONFIG
        SKIA_BUILD_ENABLE_FONTMGR_ANDROID
        SKIA_BUILD_ENABLE_FONTMGR_WIN
        SKIA_BUILD_ENABLE_FONTMGR_WIN_GDI
        SKIA_BUILD_USE_HARFBUZZ
        SKIA_BUILD_USE_SYSTEM_HARFBUZZ
        SKIA_BUILD_USE_EXPAT
        SKIA_BUILD_USE_SYSTEM_EXPAT
        SKIA_BUILD_USE_ICU
        SKIA_BUILD_USE_SYSTEM_ICU
        SKIA_BUILD_USE_ZLIB
        SKIA_BUILD_USE_SYSTEM_ZLIB
        SKIA_BUILD_USE_LIBPNG_DECODE
        SKIA_BUILD_USE_LIBPNG_ENCODE
        SKIA_BUILD_USE_SYSTEM_LIBPNG
        SKIA_BUILD_USE_REPOSITORY_ZLIB
        SKIA_BUILD_USE_REPOSITORY_LIBPNG
        SKIA_BUILD_TARGET_OS
        SKIA_BUILD_TARGET_CPU
        SKIA_BUILD_GL_STANDARD
        SKIA_BUILD_NDK_API)
      unset(${SKIA_BUILD_FIELD})
    endforeach()

    include("${SKIA_SELECTED_BUILD_CONFIG}")

    foreach(SKIA_REQUIRED_BUILD_FIELD
        SKIA_BUILD_CONFIG_VERSION
        SKIA_BUILD_UPSTREAM_REVISION
        SKIA_BUILD_PLATFORM
        SKIA_BUILD_ARCHITECTURE
        SKIA_BUILD_LIBRARY_SHA256
        SKIA_BUILD_ENABLE_GPU
        SKIA_BUILD_USE_GL
        SKIA_BUILD_USE_EGL
        SKIA_BUILD_USE_METAL
        SKIA_BUILD_USE_VULKAN
        SKIA_BUILD_USE_OPENCL
        SKIA_BUILD_USE_WEBGL
        SKIA_BUILD_USE_ANGLE
        SKIA_BUILD_USE_DAWN
        SKIA_BUILD_USE_DIRECT3D
        SKIA_BUILD_USE_VMA
        SKIA_BUILD_USE_X11
        SKIA_BUILD_USE_FONTHOST_MAC
        SKIA_BUILD_USE_FREETYPE
        SKIA_BUILD_USE_SYSTEM_FREETYPE2
        SKIA_BUILD_USE_FONTCONFIG
        SKIA_BUILD_ENABLE_FONTMGR_FONTCONFIG
        SKIA_BUILD_ENABLE_FONTMGR_ANDROID
        SKIA_BUILD_ENABLE_FONTMGR_WIN
        SKIA_BUILD_ENABLE_FONTMGR_WIN_GDI
        SKIA_BUILD_USE_HARFBUZZ
        SKIA_BUILD_USE_SYSTEM_HARFBUZZ
        SKIA_BUILD_USE_EXPAT
        SKIA_BUILD_USE_SYSTEM_EXPAT
        SKIA_BUILD_USE_ICU
        SKIA_BUILD_USE_SYSTEM_ICU
        SKIA_BUILD_USE_ZLIB
        SKIA_BUILD_USE_SYSTEM_ZLIB
        SKIA_BUILD_USE_LIBPNG_DECODE
        SKIA_BUILD_USE_LIBPNG_ENCODE
        SKIA_BUILD_USE_SYSTEM_LIBPNG
        SKIA_BUILD_USE_REPOSITORY_ZLIB
        SKIA_BUILD_USE_REPOSITORY_LIBPNG
        SKIA_BUILD_TARGET_OS
        SKIA_BUILD_TARGET_CPU
        SKIA_BUILD_GL_STANDARD
        SKIA_BUILD_NDK_API)
      if(NOT DEFINED ${SKIA_REQUIRED_BUILD_FIELD})
        message(FATAL_ERROR
          "Skia build metadata '${SKIA_SELECTED_BUILD_CONFIG}' is missing ${SKIA_REQUIRED_BUILD_FIELD}"
        )
      endif()
    endforeach()

    if(NOT SKIA_BUILD_CONFIG_VERSION STREQUAL "1")
      message(FATAL_ERROR
        "Unsupported Skia build-config version '${SKIA_BUILD_CONFIG_VERSION}' in '${SKIA_SELECTED_BUILD_CONFIG}'; expected 1"
      )
    endif()
    if(NOT SKIA_BUILD_PLATFORM STREQUAL SKIA_PLATFORM)
      message(FATAL_ERROR
        "Skia build-config platform mismatch: selected ${SKIA_PLATFORM}, metadata contains ${SKIA_BUILD_PLATFORM}"
      )
    endif()
    if(NOT SKIA_BUILD_ARCHITECTURE STREQUAL SKIA_ARCH)
      message(FATAL_ERROR
        "Skia build-config architecture mismatch: selected ${SKIA_ARCH}, metadata contains ${SKIA_BUILD_ARCHITECTURE}"
      )
    endif()

    file(SHA256 "${SKIA_LIBRARY_ABSOLUTE}" SKIA_LIBRARY_ACTUAL_SHA256)
    if(NOT SKIA_LIBRARY_ACTUAL_SHA256 STREQUAL SKIA_BUILD_LIBRARY_SHA256)
      message(FATAL_ERROR
        "Skia library SHA-256 mismatch: metadata contains ${SKIA_BUILD_LIBRARY_SHA256}, library is ${SKIA_LIBRARY_ACTUAL_SHA256}"
      )
    endif()

    skia_classify_link_requirements(SKIA_LOGICAL_REQUIREMENTS "${SKIA_PLATFORM}" "${SKIA_ARCH}")
    if("repository-zlib" IN_LIST SKIA_LOGICAL_REQUIREMENTS)
      find_package(ZLIB REQUIRED MODULE)
    endif()
    if("repository-png" IN_LIST SKIA_LOGICAL_REQUIREMENTS)
      find_package(PNG REQUIRED MODULE)
    endif()
    skia_resolve_link_dependencies(SKIA_INTERFACE_LIBRARIES "${SKIA_PLATFORM}" "${SKIA_ARCH}")

    skia_platform_compile_definition(SKIA_PLATFORM_COMPILE_DEFINITION "${SKIA_PLATFORM}")
    list(APPEND SKIA_INTERFACE_COMPILE_DEFINITIONS "${SKIA_PLATFORM_COMPILE_DEFINITION}")
    if(SKIA_BUILD_USE_GL)
      list(APPEND SKIA_INTERFACE_COMPILE_DEFINITIONS SK_GL)
    endif()
    if(SKIA_BUILD_USE_METAL)
      list(APPEND SKIA_INTERFACE_COMPILE_DEFINITIONS SK_METAL)
    endif()
    if(SKIA_BUILD_USE_VULKAN)
      list(APPEND SKIA_INTERFACE_COMPILE_DEFINITIONS SK_VULKAN)
    endif()
    list(REMOVE_DUPLICATES SKIA_INTERFACE_COMPILE_DEFINITIONS)
    set(SKIA_METADATA_DRIVEN ON)
  elseif(SKIA_MANAGED_LIBRARY AND SKIA_REQUIRE_BUILD_CONFIG)
    message(FATAL_ERROR
      "Repository-managed Skia prebuilt '${SKIA_LIBRARY}' is missing required '${SKIA_SELECTED_BUILD_CONFIG}'"
    )
  else()
    if(SKIA_MANAGED_LIBRARY)
      message(WARNING
        "Repository-managed legacy Skia prebuilt has no SkiaBuildConfig.cmake; using bounded legacy link behavior"
      )
    else()
      message(WARNING
        "External Skia library has no SkiaBuildConfig.cmake; backend link dependencies cannot be inferred and legacy behavior is used"
      )
    endif()
    if(NOT SKIA_PLATFORM STREQUAL "wasm")
      find_package(ZLIB REQUIRED MODULE)
      find_package(PNG REQUIRED MODULE)
      set(SKIA_INTERFACE_LIBRARIES "PNG::PNG;ZLIB::ZLIB")
    endif()
  endif()

  add_library(Skia::Skia UNKNOWN IMPORTED)
  set_target_properties(Skia::Skia PROPERTIES
    IMPORTED_LOCATION "${SKIA_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${SKIA_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${SKIA_INTERFACE_LIBRARIES}"
    INTERFACE_COMPILE_DEFINITIONS "${SKIA_INTERFACE_COMPILE_DEFINITIONS}"
  )
endif()
