# SPDX-FileCopyrightText: 2026 Amalgam Solucoes em TI Ltda.
# SPDX-License-Identifier: MIT

include_guard(GLOBAL)

function(_skia_append_requirement list_var requirement)
  set(items "${${list_var}}")
  list(APPEND items "${requirement}")
  list(REMOVE_DUPLICATES items)
  set(${list_var} "${items}" PARENT_SCOPE)
endfunction()

function(skia_classify_link_requirements output_var platform architecture)
  set(requirements "")

  if(SKIA_BUILD_USE_ANGLE)
    message(FATAL_ERROR "Skia ANGLE linkage is not supported by the depot-tools v1 link contract")
  endif()
  if(SKIA_BUILD_USE_DAWN)
    message(FATAL_ERROR "Skia Dawn linkage is not supported by the depot-tools v1 link contract")
  endif()
  if(SKIA_BUILD_USE_DIRECT3D)
    message(FATAL_ERROR "Skia Direct3D linkage is not supported by the depot-tools v1 link contract")
  endif()
  if(SKIA_BUILD_USE_HARFBUZZ AND SKIA_BUILD_USE_SYSTEM_HARFBUZZ)
    message(FATAL_ERROR "System HarfBuzz linkage is not supported by the depot-tools v1 link contract")
  endif()
  if(SKIA_BUILD_USE_EXPAT AND SKIA_BUILD_USE_SYSTEM_EXPAT)
    message(FATAL_ERROR "System Expat linkage is not supported by the depot-tools v1 link contract")
  endif()
  if(SKIA_BUILD_USE_ICU AND SKIA_BUILD_USE_SYSTEM_ICU)
    message(FATAL_ERROR "System ICU linkage is not supported by the depot-tools v1 link contract")
  endif()

  if(SKIA_BUILD_USE_METAL AND
      NOT platform STREQUAL "macos" AND
      NOT platform STREQUAL "ios" AND
      NOT platform STREQUAL "ios-simulator")
    message(FATAL_ERROR "Skia Metal metadata is not valid for platform '${platform}'")
  endif()

  if(SKIA_BUILD_USE_WEBGL AND NOT platform STREQUAL "wasm")
    message(FATAL_ERROR "Skia WebGL metadata is not valid for platform '${platform}'")
  endif()

  if(SKIA_BUILD_USE_REPOSITORY_LIBPNG AND
      (SKIA_BUILD_USE_LIBPNG_DECODE OR SKIA_BUILD_USE_LIBPNG_ENCODE))
    _skia_append_requirement(requirements repository-png)
  endif()
  if(SKIA_BUILD_USE_ZLIB AND SKIA_BUILD_USE_REPOSITORY_ZLIB)
    _skia_append_requirement(requirements repository-zlib)
  endif()

  if(platform STREQUAL "macos")
    _skia_append_requirement(requirements apple-application-services)
    if(SKIA_BUILD_USE_FONTHOST_MAC)
      _skia_append_requirement(requirements apple-appkit)
    endif()
    if(SKIA_BUILD_USE_GL)
      _skia_append_requirement(requirements apple-opengl)
    endif()
    if(SKIA_BUILD_USE_METAL)
      _skia_append_requirement(requirements apple-metal)
      _skia_append_requirement(requirements apple-foundation)
    endif()
  elseif(platform STREQUAL "ios" OR platform STREQUAL "ios-simulator")
    _skia_append_requirement(requirements apple-core-foundation)
    _skia_append_requirement(requirements apple-image-io)
    _skia_append_requirement(requirements apple-mobile-core-services)
    if(SKIA_BUILD_USE_FONTHOST_MAC)
      _skia_append_requirement(requirements apple-core-graphics)
      _skia_append_requirement(requirements apple-core-text)
      _skia_append_requirement(requirements apple-uikit)
    endif()
    if(SKIA_BUILD_USE_METAL)
      _skia_append_requirement(requirements apple-metal)
      _skia_append_requirement(requirements apple-foundation)
    endif()
  elseif(platform STREQUAL "linux")
    _skia_append_requirement(requirements toolchain-dl)
    if(SKIA_BUILD_USE_GL AND SKIA_BUILD_USE_EGL)
      _skia_append_requirement(requirements toolchain-egl)
      _skia_append_requirement(requirements toolchain-glesv2)
    elseif(SKIA_BUILD_USE_GL AND SKIA_BUILD_USE_X11)
      _skia_append_requirement(requirements toolchain-opengl)
    endif()
    if(SKIA_BUILD_ENABLE_FONTMGR_FONTCONFIG)
      _skia_append_requirement(requirements toolchain-fontconfig)
    endif()
    if(SKIA_BUILD_USE_FREETYPE AND SKIA_BUILD_USE_SYSTEM_FREETYPE2)
      _skia_append_requirement(requirements toolchain-freetype)
    endif()
  elseif(platform STREQUAL "android")
    _skia_append_requirement(requirements toolchain-android-log)
    if(SKIA_BUILD_USE_GL)
      _skia_append_requirement(requirements toolchain-egl)
      _skia_append_requirement(requirements toolchain-glesv2)
    endif()
    if(SKIA_BUILD_NDK_API MATCHES "^[0-9]+$" AND SKIA_BUILD_NDK_API GREATER_EQUAL 26)
      _skia_append_requirement(requirements toolchain-android)
    endif()
  elseif(platform STREQUAL "windows")
    _skia_append_requirement(requirements windows-fontsub)
    _skia_append_requirement(requirements windows-ole32)
    _skia_append_requirement(requirements windows-oleaut32)
    _skia_append_requirement(requirements windows-user32)
    _skia_append_requirement(requirements windows-usp10)
    if(SKIA_BUILD_ENABLE_FONTMGR_WIN_GDI)
      _skia_append_requirement(requirements windows-gdi32)
    endif()
    if(SKIA_BUILD_USE_GL AND (architecture STREQUAL "x86" OR architecture STREQUAL "x64"))
      _skia_append_requirement(requirements windows-opengl32)
    endif()
  elseif(NOT platform STREQUAL "wasm")
    message(FATAL_ERROR "Unsupported Skia metadata platform '${platform}'")
  endif()

  # The current Vulkan target consumes caller-provided entry points and bundles
  # VMA. The current OpenCL flag does not add a dependency to //:skia. WebGL is
  # supplied by Emscripten. These flags are deliberately classified without a
  # loader/library requirement.
  set(${output_var} "${requirements}" PARENT_SCOPE)
endfunction()

function(_skia_resolve_apple_framework output_var framework_name)
  string(MAKE_C_IDENTIFIER "SKIA_${framework_name}_FRAMEWORK" cache_var)
  find_library(${cache_var} NAMES "${framework_name}")
  if(NOT ${cache_var})
    message(FATAL_ERROR "Skia requires the ${framework_name} platform framework")
  endif()
  set(${output_var} "${${cache_var}}" PARENT_SCOPE)
endfunction()

function(skia_resolve_link_dependencies output_var platform architecture)
  skia_classify_link_requirements(logical_requirements "${platform}" "${architecture}")
  set(link_items "")

  foreach(requirement IN LISTS logical_requirements)
    if(requirement STREQUAL "repository-png")
      list(APPEND link_items PNG::PNG)
    elseif(requirement STREQUAL "repository-zlib")
      list(APPEND link_items ZLIB::ZLIB)
    elseif(requirement MATCHES "^apple-(.+)$")
      if(requirement STREQUAL "apple-application-services")
        set(framework_name ApplicationServices)
      elseif(requirement STREQUAL "apple-appkit")
        set(framework_name AppKit)
      elseif(requirement STREQUAL "apple-opengl")
        set(framework_name OpenGL)
      elseif(requirement STREQUAL "apple-metal")
        set(framework_name Metal)
      elseif(requirement STREQUAL "apple-foundation")
        set(framework_name Foundation)
      elseif(requirement STREQUAL "apple-core-foundation")
        set(framework_name CoreFoundation)
      elseif(requirement STREQUAL "apple-image-io")
        set(framework_name ImageIO)
      elseif(requirement STREQUAL "apple-mobile-core-services")
        set(framework_name MobileCoreServices)
      elseif(requirement STREQUAL "apple-core-graphics")
        set(framework_name CoreGraphics)
      elseif(requirement STREQUAL "apple-core-text")
        set(framework_name CoreText)
      elseif(requirement STREQUAL "apple-uikit")
        set(framework_name UIKit)
      else()
        message(FATAL_ERROR "Unknown Skia Apple requirement '${requirement}'")
      endif()
      _skia_resolve_apple_framework(framework "${framework_name}")
      list(APPEND link_items "${framework}")
    elseif(requirement STREQUAL "toolchain-dl")
      if(CMAKE_DL_LIBS)
        list(APPEND link_items "${CMAKE_DL_LIBS}")
      endif()
    elseif(requirement STREQUAL "toolchain-egl")
      list(APPEND link_items EGL)
    elseif(requirement STREQUAL "toolchain-glesv2")
      list(APPEND link_items GLESv2)
    elseif(requirement STREQUAL "toolchain-opengl")
      list(APPEND link_items GL)
    elseif(requirement STREQUAL "toolchain-fontconfig")
      list(APPEND link_items fontconfig)
    elseif(requirement STREQUAL "toolchain-freetype")
      list(APPEND link_items freetype)
    elseif(requirement STREQUAL "toolchain-android-log")
      list(APPEND link_items log)
    elseif(requirement STREQUAL "toolchain-android")
      list(APPEND link_items android)
    elseif(requirement MATCHES "^windows-(.+)$")
      if(requirement STREQUAL "windows-fontsub")
        list(APPEND link_items FontSub)
      elseif(requirement STREQUAL "windows-ole32")
        list(APPEND link_items Ole32)
      elseif(requirement STREQUAL "windows-oleaut32")
        list(APPEND link_items OleAut32)
      elseif(requirement STREQUAL "windows-user32")
        list(APPEND link_items User32)
      elseif(requirement STREQUAL "windows-usp10")
        list(APPEND link_items Usp10)
      elseif(requirement STREQUAL "windows-gdi32")
        list(APPEND link_items Gdi32)
      elseif(requirement STREQUAL "windows-opengl32")
        list(APPEND link_items OpenGL32)
      else()
        message(FATAL_ERROR "Unknown Skia Windows requirement '${requirement}'")
      endif()
    else()
      message(FATAL_ERROR "Unknown logical Skia link requirement '${requirement}'")
    endif()
  endforeach()

  list(REMOVE_DUPLICATES link_items)
  set(${output_var} "${link_items}" PARENT_SCOPE)
endfunction()
