# SPDX-FileCopyrightText: 2026 Amalgam Solucoes em TI Ltda.
# SPDX-License-Identifier: MIT
#

get_filename_component(TCVM_SQLITE3_AUTOFETCH_DIR "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
get_filename_component(TCVM_SQLITE3_AUTOFETCH_DEP_DIR "${TCVM_SQLITE3_AUTOFETCH_DIR}/.." ABSOLUTE)
set(TCVM_SQLITE3_RELEASE_HELPER "${TCVM_SQLITE3_AUTOFETCH_DEP_DIR}/../cmake/DepotDependencyRelease.cmake")
if(EXISTS "${TCVM_SQLITE3_RELEASE_HELPER}")
  include("${TCVM_SQLITE3_RELEASE_HELPER}")
endif()

function(tcvm_auto_fetch_sqlite3)
  set(TCVM_SQLITE3_DEP_DIR "${TCVM_SQLITE3_AUTOFETCH_DEP_DIR}")
  set(TCVM_SQLITE3_LOCAL_ROOT "${TCVM_SQLITE3_DEP_DIR}/local")

  if(NOT DEFINED SQLITE3_RELEASE_TAG AND DEFINED ENV{SQLITE3_RELEASE_TAG})
    set(SQLITE3_RELEASE_TAG "$ENV{SQLITE3_RELEASE_TAG}")
  elseif(NOT DEFINED SQLITE3_RELEASE_TAG)
    if(COMMAND tcvm_get_dependency_release)
      tcvm_get_dependency_release(sqlite3 SQLITE3_RELEASE_TAG "sqlite3-3.32.3")
    else()
      set(SQLITE3_RELEASE_TAG "sqlite3-3.32.3")
    endif()
  endif()

  if(NOT DEFINED SQLITE3_GITHUB_REPO AND DEFINED ENV{SQLITE3_GITHUB_REPO})
    set(SQLITE3_GITHUB_REPO "$ENV{SQLITE3_GITHUB_REPO}")
  elseif(NOT DEFINED SQLITE3_GITHUB_REPO)
    set(SQLITE3_GITHUB_REPO "TotalCross/totalcross-depot-tools")
  endif()

  if(NOT DEFINED SQLITE3_GITHUB_TOKEN_ENV AND DEFINED ENV{SQLITE3_GITHUB_TOKEN_ENV})
    set(SQLITE3_GITHUB_TOKEN_ENV "$ENV{SQLITE3_GITHUB_TOKEN_ENV}")
  elseif(NOT DEFINED SQLITE3_GITHUB_TOKEN_ENV)
    set(SQLITE3_GITHUB_TOKEN_ENV "SQLITE3_GITHUB_TOKEN")
  endif()

  if(NOT SQLITE3_GITHUB_REPO MATCHES "^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
    message(FATAL_ERROR "Invalid SQLite3 GitHub repository value. Expected OWNER/REPO.")
  endif()

  foreach(TCVM_SQLITE3_RELEASE_TAG_FORBIDDEN " " "{" "}" "/" "\\")
    string(FIND "${SQLITE3_RELEASE_TAG}" "${TCVM_SQLITE3_RELEASE_TAG_FORBIDDEN}" TCVM_SQLITE3_RELEASE_TAG_FORBIDDEN_INDEX)
    if(NOT TCVM_SQLITE3_RELEASE_TAG_FORBIDDEN_INDEX EQUAL -1)
      message(FATAL_ERROR "Invalid SQLite3 release tag value: ${SQLITE3_RELEASE_TAG}")
    endif()
  endforeach()
  string(FIND "${SQLITE3_RELEASE_TAG}" ".." TCVM_SQLITE3_RELEASE_TAG_PARENT_INDEX)
  if(NOT TCVM_SQLITE3_RELEASE_TAG_PARENT_INDEX EQUAL -1)
    message(FATAL_ERROR "Invalid SQLite3 release tag value: ${SQLITE3_RELEASE_TAG}")
  endif()

  string(SHA256 TCVM_SQLITE3_REPO_HASH "${SQLITE3_GITHUB_REPO}")
  string(SUBSTRING "${TCVM_SQLITE3_REPO_HASH}" 0 12 TCVM_SQLITE3_REPO_HASH)
  set(TCVM_SQLITE3_NAMESPACE "${SQLITE3_RELEASE_TAG}-${TCVM_SQLITE3_REPO_HASH}")

  if(DEFINED ANDROID_ABI)
    set(TCVM_SQLITE3_PLATFORM "android")
    set(TCVM_SQLITE3_ARCH "${ANDROID_ABI}")
  elseif(APPLE AND (CMAKE_SYSTEM_NAME STREQUAL "iOS" OR CMAKE_OSX_SYSROOT MATCHES "[Ii][Pp]hone"))
    if(CMAKE_OSX_SYSROOT MATCHES "[Ii][Pp]hone[Ss]imulator")
      set(TCVM_SQLITE3_PLATFORM "ios-simulator")
    else()
      set(TCVM_SQLITE3_PLATFORM "ios")
    endif()
    set(TCVM_SQLITE3_ARCH "${CMAKE_OSX_ARCHITECTURES}")
    if(TCVM_SQLITE3_ARCH)
      list(LENGTH TCVM_SQLITE3_ARCH TCVM_SQLITE3_ARCH_LEN)
      if(TCVM_SQLITE3_ARCH_LEN GREATER 1)
        message(FATAL_ERROR "SQLite3 auto-fetch expects a single iOS architecture, got: ${TCVM_SQLITE3_ARCH}")
      endif()
      list(GET TCVM_SQLITE3_ARCH 0 TCVM_SQLITE3_ARCH)
    else()
      set(TCVM_SQLITE3_ARCH "arm64")
    endif()
    if(TCVM_SQLITE3_ARCH STREQUAL "aarch64")
      set(TCVM_SQLITE3_ARCH "arm64")
    endif()
  elseif(WIN32)
    set(TCVM_SQLITE3_PLATFORM "windows")
    set(TCVM_SQLITE3_WINDOWS_PLATFORM "${CMAKE_VS_PLATFORM_NAME}")
    if(NOT TCVM_SQLITE3_WINDOWS_PLATFORM)
      set(TCVM_SQLITE3_WINDOWS_PLATFORM "${CMAKE_GENERATOR_PLATFORM}")
    endif()
    string(TOLOWER "${TCVM_SQLITE3_WINDOWS_PLATFORM}" TCVM_SQLITE3_WINDOWS_PLATFORM_LOWER)
    if(TCVM_SQLITE3_WINDOWS_PLATFORM_LOWER STREQUAL "win32")
      set(TCVM_SQLITE3_ARCH "x86")
    elseif(TCVM_SQLITE3_WINDOWS_PLATFORM_LOWER STREQUAL "x64")
      set(TCVM_SQLITE3_ARCH "x64")
    elseif(TCVM_SQLITE3_WINDOWS_PLATFORM_LOWER STREQUAL "arm64")
      set(TCVM_SQLITE3_ARCH "arm64")
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
      set(TCVM_SQLITE3_ARCH "x64")
    else()
      set(TCVM_SQLITE3_ARCH "x86")
    endif()
  elseif(APPLE)
    set(TCVM_SQLITE3_PLATFORM "macos")
    set(TCVM_SQLITE3_ARCH "${CMAKE_OSX_ARCHITECTURES}")
    if(TCVM_SQLITE3_ARCH)
      list(LENGTH TCVM_SQLITE3_ARCH TCVM_SQLITE3_ARCH_LEN)
      if(TCVM_SQLITE3_ARCH_LEN GREATER 1)
        message(FATAL_ERROR "SQLite3 auto-fetch expects a single macOS architecture, got: ${TCVM_SQLITE3_ARCH}")
      endif()
      list(GET TCVM_SQLITE3_ARCH 0 TCVM_SQLITE3_ARCH)
    else()
      set(TCVM_SQLITE3_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
    endif()

    if(TCVM_SQLITE3_ARCH STREQUAL "amd64")
      set(TCVM_SQLITE3_ARCH "x86_64")
    elseif(TCVM_SQLITE3_ARCH STREQUAL "aarch64")
      set(TCVM_SQLITE3_ARCH "arm64")
    endif()
  elseif(UNIX AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(TCVM_SQLITE3_PLATFORM "linux")
    set(TCVM_SQLITE3_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
    if(TCVM_SQLITE3_ARCH STREQUAL "amd64")
      set(TCVM_SQLITE3_ARCH "x86_64")
    elseif(TCVM_SQLITE3_ARCH STREQUAL "arm64")
      set(TCVM_SQLITE3_ARCH "aarch64")
    elseif(TCVM_SQLITE3_ARCH STREQUAL "arm" OR TCVM_SQLITE3_ARCH STREQUAL "armv7")
      set(TCVM_SQLITE3_ARCH "armv7l")
    endif()
  else()
    message(FATAL_ERROR "Unable to auto-fetch SQLite3 for ${CMAKE_SYSTEM_NAME}/${CMAKE_SYSTEM_PROCESSOR}")
  endif()

  set(TCVM_DEFAULT_SQLITE3_DIR "${TCVM_SQLITE3_LOCAL_ROOT}/${TCVM_SQLITE3_NAMESPACE}/${TCVM_SQLITE3_PLATFORM}/${TCVM_SQLITE3_ARCH}")

  if(DEFINED SQLITE3_DIR AND NOT SQLITE3_DIR STREQUAL "${TCVM_DEFAULT_SQLITE3_DIR}")
    return()
  endif()

  set(SQLITE3_DIR "${TCVM_DEFAULT_SQLITE3_DIR}" CACHE PATH "SQLite3 prebuilt directory" FORCE)

  if(WIN32)
    set(TCVM_SQLITE3_LIBRARY "${SQLITE3_DIR}/lib/sqlite3.lib")
  else()
    set(TCVM_SQLITE3_LIBRARY "${SQLITE3_DIR}/lib/libsqlite3.a")
  endif()

  if(EXISTS "${SQLITE3_DIR}/include/sqlite3.h" AND EXISTS "${TCVM_SQLITE3_LIBRARY}")
    return()
  endif()

  find_program(TCVM_BASH_EXECUTABLE bash)
  if(NOT TCVM_BASH_EXECUTABLE)
    message(FATAL_ERROR "Unable to auto-fetch SQLite3 because 'bash' was not found")
  endif()

  set(TCVM_SQLITE3_FETCH_SCRIPT "${TCVM_SQLITE3_DEP_DIR}/fetch.sh")
  if(NOT EXISTS "${TCVM_SQLITE3_FETCH_SCRIPT}")
    message(FATAL_ERROR "Unable to auto-fetch SQLite3 because '${TCVM_SQLITE3_FETCH_SCRIPT}' does not exist")
  endif()

  message(STATUS "SQLite3 artifacts not found locally. Fetching ${SQLITE3_GITHUB_REPO}@${SQLITE3_RELEASE_TAG}/${TCVM_SQLITE3_PLATFORM}/${TCVM_SQLITE3_ARCH}...")

  execute_process(
    COMMAND
      "${TCVM_BASH_EXECUTABLE}" "${TCVM_SQLITE3_FETCH_SCRIPT}"
      --platform "${TCVM_SQLITE3_PLATFORM}"
      --arch "${TCVM_SQLITE3_ARCH}"
      --release-tag "${SQLITE3_RELEASE_TAG}"
      --github-repo "${SQLITE3_GITHUB_REPO}"
      --github-token-env "${SQLITE3_GITHUB_TOKEN_ENV}"
      --dest "${TCVM_SQLITE3_LOCAL_ROOT}"
    WORKING_DIRECTORY "${TCVM_SQLITE3_DEP_DIR}"
    RESULT_VARIABLE TCVM_SQLITE3_FETCH_RESULT
    OUTPUT_VARIABLE TCVM_SQLITE3_FETCH_STDOUT
    ERROR_VARIABLE TCVM_SQLITE3_FETCH_STDERR
  )

  if(NOT TCVM_SQLITE3_FETCH_RESULT EQUAL 0)
    message(FATAL_ERROR
      "Failed to auto-fetch SQLite3.\n"
      "stdout:\n${TCVM_SQLITE3_FETCH_STDOUT}\n"
      "stderr:\n${TCVM_SQLITE3_FETCH_STDERR}"
    )
  endif()

  message(STATUS "${TCVM_SQLITE3_FETCH_STDOUT}")
endfunction()
