# SPDX-FileCopyrightText: 2026 Amalgam Solucoes em TI Ltda.
# SPDX-License-Identifier: MIT
get_filename_component(TC_QRCODEGEN_AUTOFETCH_DIR "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
get_filename_component(TC_QRCODEGEN_DEP_DIR "${TC_QRCODEGEN_AUTOFETCH_DIR}/.." ABSOLUTE)
set(TC_QRCODEGEN_RELEASE_HELPER "${TC_QRCODEGEN_DEP_DIR}/../cmake/DepotDependencyRelease.cmake")
if(EXISTS "${TC_QRCODEGEN_RELEASE_HELPER}")
  include("${TC_QRCODEGEN_RELEASE_HELPER}")
endif()

function(tcvm_auto_fetch_qrcodegen)
  if(NOT DEFINED QRCODEGEN_RELEASE_TAG AND DEFINED ENV{QRCODEGEN_RELEASE_TAG})
    set(QRCODEGEN_RELEASE_TAG "$ENV{QRCODEGEN_RELEASE_TAG}")
  elseif(NOT DEFINED QRCODEGEN_RELEASE_TAG)
    if(COMMAND tcvm_get_dependency_release)
      tcvm_get_dependency_release(qrcodegen QRCODEGEN_RELEASE_TAG "")
    else()
      set(QRCODEGEN_RELEASE_TAG "")
    endif()
  endif()

  if(NOT QRCODEGEN_RELEASE_TAG)
    message(FATAL_ERROR
      "No qrcodegen release is pinned in deps.yml. Set QRCODEGEN_RELEASE_TAG for an explicit release handoff.")
  endif()
  if(NOT DEFINED QRCODEGEN_GITHUB_REPO AND DEFINED ENV{QRCODEGEN_GITHUB_REPO})
    set(QRCODEGEN_GITHUB_REPO "$ENV{QRCODEGEN_GITHUB_REPO}")
  elseif(NOT DEFINED QRCODEGEN_GITHUB_REPO)
    set(QRCODEGEN_GITHUB_REPO "TotalCross/totalcross-depot-tools")
  endif()
  include("${TC_QRCODEGEN_DEP_DIR}/cmake/FindQRCodeGen.cmake")
  if(QRCodeGen_FOUND)
    return()
  endif()
  find_program(TC_QRCODEGEN_BASH bash REQUIRED)
  execute_process(COMMAND "${TC_QRCODEGEN_BASH}" "${TC_QRCODEGEN_DEP_DIR}/fetch.sh"
    --platform "${QRCodeGen_PLATFORM}" --arch "${QRCodeGen_ARCH}"
    --release-tag "${QRCODEGEN_RELEASE_TAG}" --github-repo "${QRCODEGEN_GITHUB_REPO}"
    WORKING_DIRECTORY "${TC_QRCODEGEN_DEP_DIR}" RESULT_VARIABLE TC_QRCODEGEN_FETCH_RESULT)
  if(NOT TC_QRCODEGEN_FETCH_RESULT EQUAL 0)
    message(FATAL_ERROR "Failed to fetch qrcodegen prebuilt for ${QRCodeGen_PLATFORM}/${QRCodeGen_ARCH}")
  endif()
  include("${TC_QRCODEGEN_DEP_DIR}/cmake/FindQRCodeGen.cmake")
  if(NOT QRCodeGen_FOUND)
    message(FATAL_ERROR "Fetched qrcodegen artifact was not found")
  endif()
endfunction()
