# SPDX-FileCopyrightText: 2026 Amalgam Solucoes em TI Ltda.
# SPDX-License-Identifier: MIT
get_filename_component(QRCodeGen_DEPENDENCY_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(QRCodeGen_LOCAL_ROOT "${QRCodeGen_DEPENDENCY_DIR}/local")

if(DEFINED ANDROID_ABI)
  set(QRCodeGen_PLATFORM android)
  set(QRCodeGen_ARCH "${ANDROID_ABI}")
elseif(APPLE AND (CMAKE_SYSTEM_NAME STREQUAL "iOS" OR CMAKE_OSX_SYSROOT MATCHES "[Ii]phone"))
  if(CMAKE_OSX_SYSROOT MATCHES "[Ii]phone[Ss]imulator")
    set(QRCodeGen_PLATFORM ios-simulator)
  else()
    set(QRCodeGen_PLATFORM ios)
  endif()
  set(QRCodeGen_ARCH "${CMAKE_OSX_ARCHITECTURES}")
elseif(WIN32)
  set(QRCodeGen_PLATFORM windows)
  set(QRCodeGen_WINDOWS_PLATFORM "${CMAKE_VS_PLATFORM_NAME}")
  if(NOT QRCodeGen_WINDOWS_PLATFORM)
    set(QRCodeGen_WINDOWS_PLATFORM "${CMAKE_GENERATOR_PLATFORM}")
  endif()
  string(TOLOWER "${QRCodeGen_WINDOWS_PLATFORM}" QRCodeGen_WINDOWS_PLATFORM)
  if(QRCodeGen_WINDOWS_PLATFORM STREQUAL "win32")
    set(QRCodeGen_ARCH x86)
  elseif(QRCodeGen_WINDOWS_PLATFORM STREQUAL "arm64")
    set(QRCodeGen_ARCH arm64)
  elseif(QRCodeGen_WINDOWS_PLATFORM STREQUAL "x64" OR CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(QRCodeGen_ARCH x64)
  else()
    set(QRCodeGen_ARCH x86)
  endif()
elseif(APPLE)
  set(QRCodeGen_PLATFORM macos)
  set(QRCodeGen_ARCH "${CMAKE_OSX_ARCHITECTURES}")
elseif(UNIX AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(QRCodeGen_PLATFORM linux)
  set(QRCodeGen_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
else()
  message(FATAL_ERROR "Unsupported qrcodegen target ${CMAKE_SYSTEM_NAME}/${CMAKE_SYSTEM_PROCESSOR}")
endif()
if(NOT QRCodeGen_ARCH)
  set(QRCodeGen_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
endif()
list(GET QRCodeGen_ARCH 0 QRCodeGen_ARCH)
if(QRCodeGen_ARCH STREQUAL "amd64")
  set(QRCodeGen_ARCH x86_64)
elseif(QRCodeGen_ARCH STREQUAL "aarch64" AND NOT QRCodeGen_PLATFORM STREQUAL "linux")
  set(QRCodeGen_ARCH arm64)
elseif(QRCodeGen_ARCH STREQUAL "arm64" AND QRCodeGen_PLATFORM STREQUAL "linux")
  set(QRCodeGen_ARCH aarch64)
elseif(QRCodeGen_ARCH STREQUAL "arm" OR QRCodeGen_ARCH STREQUAL "armv7")
  set(QRCodeGen_ARCH armv7l)
endif()

set(QRCODEGEN_DIR "${QRCodeGen_LOCAL_ROOT}/${QRCodeGen_PLATFORM}/${QRCodeGen_ARCH}" CACHE PATH "qrcodegen prebuilt directory" FORCE)
find_path(QRCODEGEN_INCLUDE_DIR NAMES qrcodegen.h HINTS "${QRCODEGEN_DIR}/include" NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
find_library(QRCODEGEN_LIBRARY NAMES qrcodegen libqrcodegen HINTS "${QRCODEGEN_DIR}/lib" NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(QRCodeGen REQUIRED_VARS QRCODEGEN_INCLUDE_DIR QRCODEGEN_LIBRARY)
if(QRCodeGen_FOUND AND NOT TARGET QRCodeGen::QRCodeGen)
  add_library(QRCodeGen::QRCodeGen STATIC IMPORTED)
  set_target_properties(QRCodeGen::QRCodeGen PROPERTIES IMPORTED_LOCATION "${QRCODEGEN_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${QRCODEGEN_INCLUDE_DIR}")
endif()
