# Copyright (C) 2026 Amalgam Solucoes em TI Ltda
#
# SPDX-License-Identifier: LGPL-2.1-only

get_filename_component(TCVM_LIBJPEG_TURBO_AUTOFETCH_DIR "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
get_filename_component(TCVM_LIBJPEG_TURBO_AUTOFETCH_DEP_DIR "${TCVM_LIBJPEG_TURBO_AUTOFETCH_DIR}/.." ABSOLUTE)
set(TCVM_LIBJPEG_TURBO_RELEASE_HELPER "${TCVM_LIBJPEG_TURBO_AUTOFETCH_DEP_DIR}/../cmake/DepotDependencyRelease.cmake")
if(EXISTS "${TCVM_LIBJPEG_TURBO_RELEASE_HELPER}")
  include("${TCVM_LIBJPEG_TURBO_RELEASE_HELPER}")
endif()

function(tcvm_auto_fetch_libjpeg_turbo)
  set(TCVM_LIBJPEG_TURBO_DEP_DIR "${TCVM_LIBJPEG_TURBO_AUTOFETCH_DEP_DIR}")
  set(TCVM_LIBJPEG_TURBO_LOCAL_ROOT "${TCVM_LIBJPEG_TURBO_DEP_DIR}/local")

  if(NOT DEFINED LIBJPEG_TURBO_RELEASE_TAG AND DEFINED ENV{LIBJPEG_TURBO_RELEASE_TAG})
    set(LIBJPEG_TURBO_RELEASE_TAG "$ENV{LIBJPEG_TURBO_RELEASE_TAG}")
  elseif(NOT DEFINED LIBJPEG_TURBO_RELEASE_TAG)
    if(COMMAND tcvm_get_dependency_release)
      tcvm_get_dependency_release(libjpeg-turbo LIBJPEG_TURBO_RELEASE_TAG "libjpeg-turbo-3.1.4.1")
    else()
      set(LIBJPEG_TURBO_RELEASE_TAG "libjpeg-turbo-3.1.4.1")
    endif()
  endif()

  if(NOT DEFINED LIBJPEG_TURBO_GITHUB_REPO AND DEFINED ENV{LIBJPEG_TURBO_GITHUB_REPO})
    set(LIBJPEG_TURBO_GITHUB_REPO "$ENV{LIBJPEG_TURBO_GITHUB_REPO}")
  elseif(NOT DEFINED LIBJPEG_TURBO_GITHUB_REPO)
    set(LIBJPEG_TURBO_GITHUB_REPO "TotalCross/totalcross-depot-tools")
  endif()

  if(NOT DEFINED LIBJPEG_TURBO_GITHUB_TOKEN_ENV AND DEFINED ENV{LIBJPEG_TURBO_GITHUB_TOKEN_ENV})
    set(LIBJPEG_TURBO_GITHUB_TOKEN_ENV "$ENV{LIBJPEG_TURBO_GITHUB_TOKEN_ENV}")
  elseif(NOT DEFINED LIBJPEG_TURBO_GITHUB_TOKEN_ENV)
    set(LIBJPEG_TURBO_GITHUB_TOKEN_ENV "LIBJPEG_TURBO_GITHUB_TOKEN")
  endif()

  if(DEFINED ANDROID_ABI)
    set(TCVM_LIBJPEG_TURBO_PLATFORM "android")
    set(TCVM_LIBJPEG_TURBO_ARCH "${ANDROID_ABI}")
  elseif(APPLE AND (CMAKE_SYSTEM_NAME STREQUAL "iOS" OR CMAKE_OSX_SYSROOT MATCHES "[Ii][Pp]hone"))
    if(CMAKE_OSX_SYSROOT MATCHES "[Ii][Pp]hone[Ss]imulator")
      set(TCVM_LIBJPEG_TURBO_PLATFORM "ios-simulator")
    else()
      set(TCVM_LIBJPEG_TURBO_PLATFORM "ios")
    endif()
    set(TCVM_LIBJPEG_TURBO_ARCH "${CMAKE_OSX_ARCHITECTURES}")
    if(TCVM_LIBJPEG_TURBO_ARCH)
      list(LENGTH TCVM_LIBJPEG_TURBO_ARCH TCVM_LIBJPEG_TURBO_ARCH_LEN)
      if(TCVM_LIBJPEG_TURBO_ARCH_LEN GREATER 1)
        message(FATAL_ERROR "libjpeg-turbo auto-fetch expects a single iOS architecture, got: ${TCVM_LIBJPEG_TURBO_ARCH}")
      endif()
      list(GET TCVM_LIBJPEG_TURBO_ARCH 0 TCVM_LIBJPEG_TURBO_ARCH)
    else()
      set(TCVM_LIBJPEG_TURBO_ARCH "arm64")
    endif()
    if(TCVM_LIBJPEG_TURBO_ARCH STREQUAL "aarch64")
      set(TCVM_LIBJPEG_TURBO_ARCH "arm64")
    endif()
  elseif(WIN32)
    set(TCVM_LIBJPEG_TURBO_PLATFORM "windows")
    set(TCVM_LIBJPEG_TURBO_WINDOWS_PLATFORM "${CMAKE_VS_PLATFORM_NAME}")
    if(NOT TCVM_LIBJPEG_TURBO_WINDOWS_PLATFORM)
      set(TCVM_LIBJPEG_TURBO_WINDOWS_PLATFORM "${CMAKE_GENERATOR_PLATFORM}")
    endif()
    string(TOLOWER "${TCVM_LIBJPEG_TURBO_WINDOWS_PLATFORM}" TCVM_LIBJPEG_TURBO_WINDOWS_PLATFORM_LOWER)
    if(TCVM_LIBJPEG_TURBO_WINDOWS_PLATFORM_LOWER STREQUAL "win32")
      set(TCVM_LIBJPEG_TURBO_ARCH "x86")
    elseif(TCVM_LIBJPEG_TURBO_WINDOWS_PLATFORM_LOWER STREQUAL "x64")
      set(TCVM_LIBJPEG_TURBO_ARCH "x64")
    elseif(TCVM_LIBJPEG_TURBO_WINDOWS_PLATFORM_LOWER STREQUAL "arm64")
      set(TCVM_LIBJPEG_TURBO_ARCH "arm64")
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
      set(TCVM_LIBJPEG_TURBO_ARCH "x64")
    else()
      set(TCVM_LIBJPEG_TURBO_ARCH "x86")
    endif()
  elseif(APPLE)
    set(TCVM_LIBJPEG_TURBO_PLATFORM "macos")
    set(TCVM_LIBJPEG_TURBO_ARCH "${CMAKE_OSX_ARCHITECTURES}")
    if(TCVM_LIBJPEG_TURBO_ARCH)
      list(LENGTH TCVM_LIBJPEG_TURBO_ARCH TCVM_LIBJPEG_TURBO_ARCH_LEN)
      if(TCVM_LIBJPEG_TURBO_ARCH_LEN GREATER 1)
        message(FATAL_ERROR "libjpeg-turbo auto-fetch expects a single macOS architecture, got: ${TCVM_LIBJPEG_TURBO_ARCH}")
      endif()
      list(GET TCVM_LIBJPEG_TURBO_ARCH 0 TCVM_LIBJPEG_TURBO_ARCH)
    else()
      set(TCVM_LIBJPEG_TURBO_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
    endif()

    if(TCVM_LIBJPEG_TURBO_ARCH STREQUAL "amd64")
      set(TCVM_LIBJPEG_TURBO_ARCH "x86_64")
    elseif(TCVM_LIBJPEG_TURBO_ARCH STREQUAL "aarch64")
      set(TCVM_LIBJPEG_TURBO_ARCH "arm64")
    endif()
  elseif(UNIX AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(TCVM_LIBJPEG_TURBO_PLATFORM "linux")
    set(TCVM_LIBJPEG_TURBO_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
    if(TCVM_LIBJPEG_TURBO_ARCH STREQUAL "amd64")
      set(TCVM_LIBJPEG_TURBO_ARCH "x86_64")
    elseif(TCVM_LIBJPEG_TURBO_ARCH STREQUAL "arm64")
      set(TCVM_LIBJPEG_TURBO_ARCH "aarch64")
    elseif(TCVM_LIBJPEG_TURBO_ARCH STREQUAL "arm" OR TCVM_LIBJPEG_TURBO_ARCH STREQUAL "armv7")
      set(TCVM_LIBJPEG_TURBO_ARCH "armv7l")
    endif()
  else()
    message(FATAL_ERROR "Unable to auto-fetch libjpeg-turbo for ${CMAKE_SYSTEM_NAME}/${CMAKE_SYSTEM_PROCESSOR}")
  endif()

  set(TCVM_DEFAULT_LIBJPEG_TURBO_DIR "${TCVM_LIBJPEG_TURBO_LOCAL_ROOT}/${TCVM_LIBJPEG_TURBO_PLATFORM}/${TCVM_LIBJPEG_TURBO_ARCH}")

  if(DEFINED JPEG_DIR AND NOT JPEG_DIR STREQUAL "${TCVM_DEFAULT_LIBJPEG_TURBO_DIR}")
    return()
  endif()

  set(JPEG_DIR "${TCVM_DEFAULT_LIBJPEG_TURBO_DIR}" CACHE PATH "libjpeg-turbo prebuilt directory" FORCE)

  set(TCVM_LIBJPEG_TURBO_JPEG_LIBRARY_CANDIDATES
    "${JPEG_DIR}/lib/libjpeg.a"
    "${JPEG_DIR}/lib/jpeg-static.lib"
    "${JPEG_DIR}/lib/jpeg.lib"
    "${JPEG_DIR}/lib/libjpeg.lib"
  )
  set(TCVM_LIBJPEG_TURBO_TURBOJPEG_LIBRARY_CANDIDATES
    "${JPEG_DIR}/lib/libturbojpeg.a"
    "${JPEG_DIR}/lib/turbojpeg-static.lib"
    "${JPEG_DIR}/lib/turbojpeg.lib"
    "${JPEG_DIR}/lib/libturbojpeg.lib"
  )

  set(TCVM_LIBJPEG_TURBO_HAS_JPEG_LIBRARY OFF)
  foreach(TCVM_LIBJPEG_TURBO_LIBRARY_CANDIDATE ${TCVM_LIBJPEG_TURBO_JPEG_LIBRARY_CANDIDATES})
    if(EXISTS "${TCVM_LIBJPEG_TURBO_LIBRARY_CANDIDATE}")
      set(TCVM_LIBJPEG_TURBO_HAS_JPEG_LIBRARY ON)
    endif()
  endforeach()

  set(TCVM_LIBJPEG_TURBO_HAS_TURBOJPEG_LIBRARY OFF)
  foreach(TCVM_LIBJPEG_TURBO_LIBRARY_CANDIDATE ${TCVM_LIBJPEG_TURBO_TURBOJPEG_LIBRARY_CANDIDATES})
    if(EXISTS "${TCVM_LIBJPEG_TURBO_LIBRARY_CANDIDATE}")
      set(TCVM_LIBJPEG_TURBO_HAS_TURBOJPEG_LIBRARY ON)
    endif()
  endforeach()

  if(EXISTS "${JPEG_DIR}/include/jpeglib.h"
      AND EXISTS "${JPEG_DIR}/include/jconfig.h"
      AND EXISTS "${JPEG_DIR}/include/jmorecfg.h"
      AND EXISTS "${JPEG_DIR}/include/jerror.h"
      AND EXISTS "${JPEG_DIR}/include/turbojpeg.h"
      AND TCVM_LIBJPEG_TURBO_HAS_JPEG_LIBRARY
      AND TCVM_LIBJPEG_TURBO_HAS_TURBOJPEG_LIBRARY)
    return()
  endif()

  find_program(TCVM_BASH_EXECUTABLE bash)
  if(NOT TCVM_BASH_EXECUTABLE)
    message(FATAL_ERROR "Unable to auto-fetch libjpeg-turbo because 'bash' was not found")
  endif()

  set(TCVM_LIBJPEG_TURBO_FETCH_SCRIPT "${TCVM_LIBJPEG_TURBO_DEP_DIR}/fetch.sh")
  if(NOT EXISTS "${TCVM_LIBJPEG_TURBO_FETCH_SCRIPT}")
    message(FATAL_ERROR "Unable to auto-fetch libjpeg-turbo because '${TCVM_LIBJPEG_TURBO_FETCH_SCRIPT}' does not exist")
  endif()

  message(STATUS "libjpeg-turbo artifacts not found locally. Fetching ${TCVM_LIBJPEG_TURBO_PLATFORM}/${TCVM_LIBJPEG_TURBO_ARCH}...")

  execute_process(
    COMMAND
      "${TCVM_BASH_EXECUTABLE}" "${TCVM_LIBJPEG_TURBO_FETCH_SCRIPT}"
      --platform "${TCVM_LIBJPEG_TURBO_PLATFORM}"
      --arch "${TCVM_LIBJPEG_TURBO_ARCH}"
      --release-tag "${LIBJPEG_TURBO_RELEASE_TAG}"
      --github-repo "${LIBJPEG_TURBO_GITHUB_REPO}"
      --github-token-env "${LIBJPEG_TURBO_GITHUB_TOKEN_ENV}"
      --dest "${TCVM_LIBJPEG_TURBO_LOCAL_ROOT}"
    WORKING_DIRECTORY "${TCVM_LIBJPEG_TURBO_DEP_DIR}"
    RESULT_VARIABLE TCVM_LIBJPEG_TURBO_FETCH_RESULT
    OUTPUT_VARIABLE TCVM_LIBJPEG_TURBO_FETCH_STDOUT
    ERROR_VARIABLE TCVM_LIBJPEG_TURBO_FETCH_STDERR
  )

  if(NOT TCVM_LIBJPEG_TURBO_FETCH_RESULT EQUAL 0)
    message(FATAL_ERROR
      "Failed to auto-fetch libjpeg-turbo.\n"
      "stdout:\n${TCVM_LIBJPEG_TURBO_FETCH_STDOUT}\n"
      "stderr:\n${TCVM_LIBJPEG_TURBO_FETCH_STDERR}"
    )
  endif()

  message(STATUS "${TCVM_LIBJPEG_TURBO_FETCH_STDOUT}")
endfunction()
