# Copyright (C) 2026 Amalgam Solucoes em TI Ltda
#
# SPDX-License-Identifier: LGPL-2.1-only

get_filename_component(MINIZIP_DEPENDENCY_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(MINIZIP_LOCAL_ROOT "${MINIZIP_DEPENDENCY_DIR}/local")

if(DEFINED ANDROID_ABI)
  set(MINIZIP_PLATFORM "android")
  set(MINIZIP_ARCH "${ANDROID_ABI}")
elseif(APPLE AND (CMAKE_SYSTEM_NAME STREQUAL "iOS" OR CMAKE_OSX_SYSROOT MATCHES "[Ii][Pp]hone"))
  if(CMAKE_OSX_SYSROOT MATCHES "[Ii][Pp]hone[Ss]imulator")
    set(MINIZIP_PLATFORM "ios-simulator")
  else()
    set(MINIZIP_PLATFORM "ios")
  endif()
  set(MINIZIP_ARCH "${CMAKE_OSX_ARCHITECTURES}")
  if(MINIZIP_ARCH)
    list(GET MINIZIP_ARCH 0 MINIZIP_ARCH)
  else()
    set(MINIZIP_ARCH "arm64")
  endif()
  if(MINIZIP_ARCH STREQUAL "aarch64")
    set(MINIZIP_ARCH "arm64")
  endif()
elseif(WIN32)
  set(MINIZIP_PLATFORM "windows")
  set(MINIZIP_WINDOWS_PLATFORM "${CMAKE_VS_PLATFORM_NAME}")
  if(NOT MINIZIP_WINDOWS_PLATFORM)
    set(MINIZIP_WINDOWS_PLATFORM "${CMAKE_GENERATOR_PLATFORM}")
  endif()
  string(TOLOWER "${MINIZIP_WINDOWS_PLATFORM}" MINIZIP_WINDOWS_PLATFORM_LOWER)
  if(MINIZIP_WINDOWS_PLATFORM_LOWER STREQUAL "win32")
    set(MINIZIP_ARCH "x86")
  elseif(MINIZIP_WINDOWS_PLATFORM_LOWER STREQUAL "x64")
    set(MINIZIP_ARCH "x64")
  elseif(MINIZIP_WINDOWS_PLATFORM_LOWER STREQUAL "arm64")
    set(MINIZIP_ARCH "arm64")
  elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(MINIZIP_ARCH "x64")
  else()
    set(MINIZIP_ARCH "x86")
  endif()
elseif(APPLE)
  set(MINIZIP_PLATFORM "macos")
  set(MINIZIP_ARCH "${CMAKE_OSX_ARCHITECTURES}")
  if(MINIZIP_ARCH)
    list(GET MINIZIP_ARCH 0 MINIZIP_ARCH)
  else()
    set(MINIZIP_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
  endif()
  if(MINIZIP_ARCH STREQUAL "amd64")
    set(MINIZIP_ARCH "x86_64")
  elseif(MINIZIP_ARCH STREQUAL "aarch64")
    set(MINIZIP_ARCH "arm64")
  endif()
elseif(UNIX AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(MINIZIP_PLATFORM "linux")
  set(MINIZIP_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
  if(MINIZIP_ARCH STREQUAL "amd64")
    set(MINIZIP_ARCH "x86_64")
  elseif(MINIZIP_ARCH STREQUAL "arm64")
    set(MINIZIP_ARCH "aarch64")
  elseif(MINIZIP_ARCH STREQUAL "arm" OR MINIZIP_ARCH STREQUAL "armv7")
    set(MINIZIP_ARCH "armv7l")
  endif()
endif()

set(MINIZIP_DEFAULT_DIR "${MINIZIP_LOCAL_ROOT}/${MINIZIP_PLATFORM}/${MINIZIP_ARCH}")

if(NOT DEFINED MINIZIP_DIR)
  set(MINIZIP_DIR "${MINIZIP_DEFAULT_DIR}" CACHE PATH "minizip-ng prebuilt directory")
endif()

foreach(MINIZIP_CACHED_VAR MINIZIP_INCLUDE_DIR MINIZIP_LIBRARY)
  if(DEFINED ${MINIZIP_CACHED_VAR})
    string(FIND "${${MINIZIP_CACHED_VAR}}" "${MINIZIP_DIR}" MINIZIP_CACHED_VAR_DEPOT_INDEX)
    if("${${MINIZIP_CACHED_VAR}}" MATCHES "-NOTFOUND$" OR NOT MINIZIP_CACHED_VAR_DEPOT_INDEX EQUAL 0)
      unset(${MINIZIP_CACHED_VAR} CACHE)
      unset(${MINIZIP_CACHED_VAR})
    endif()
  endif()
endforeach()

find_path(MINIZIP_INCLUDE_DIR
  NAMES mz.h
  HINTS "${MINIZIP_DIR}/include"
  NO_DEFAULT_PATH
  NO_CMAKE_FIND_ROOT_PATH
)
find_library(MINIZIP_LIBRARY
  NAMES minizip libminizip minizipstatic
  HINTS "${MINIZIP_DIR}/lib"
  NO_DEFAULT_PATH
  NO_CMAKE_FIND_ROOT_PATH
)

set(MINIZIP_ZLIB_MODULE_DIR "${MINIZIP_DEPENDENCY_DIR}/../zlib-ng/cmake")
if(EXISTS "${MINIZIP_ZLIB_MODULE_DIR}/FindZLIB.cmake")
  list(APPEND CMAKE_MODULE_PATH "${MINIZIP_ZLIB_MODULE_DIR}")
endif()
find_package(ZLIB QUIET MODULE)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MINIZIP
  REQUIRED_VARS MINIZIP_INCLUDE_DIR MINIZIP_LIBRARY
)

if(MINIZIP_FOUND AND NOT TARGET MINIZIP::MINIZIP)
  add_library(MINIZIP::MINIZIP UNKNOWN IMPORTED)
  set_target_properties(MINIZIP::MINIZIP PROPERTIES
    IMPORTED_LOCATION "${MINIZIP_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${MINIZIP_INCLUDE_DIR}"
  )
  if(TARGET ZLIB::ZLIB)
    set_target_properties(MINIZIP::MINIZIP PROPERTIES
      INTERFACE_LINK_LIBRARIES "ZLIB::ZLIB"
    )
  endif()
endif()
