get_filename_component(QRCode_DEPENDENCY_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(QRCode_LOCAL_ROOT "${QRCode_DEPENDENCY_DIR}/local")

if(DEFINED ANDROID_ABI)
  set(QRCode_PLATFORM android)
  set(QRCode_ARCH "${ANDROID_ABI}")
elseif(APPLE AND (CMAKE_SYSTEM_NAME STREQUAL "iOS" OR CMAKE_OSX_SYSROOT MATCHES "[Ii]phone"))
  if(CMAKE_OSX_SYSROOT MATCHES "[Ii]phone[Ss]imulator")
    set(QRCode_PLATFORM ios-simulator)
  else()
    set(QRCode_PLATFORM ios)
  endif()
  set(QRCode_ARCH "${CMAKE_OSX_ARCHITECTURES}")
elseif(WIN32)
  set(QRCode_PLATFORM windows)
  set(QRCode_WINDOWS_PLATFORM "${CMAKE_VS_PLATFORM_NAME}")
  if(NOT QRCode_WINDOWS_PLATFORM)
    set(QRCode_WINDOWS_PLATFORM "${CMAKE_GENERATOR_PLATFORM}")
  endif()
  string(TOLOWER "${QRCode_WINDOWS_PLATFORM}" QRCode_WINDOWS_PLATFORM)
  if(QRCode_WINDOWS_PLATFORM STREQUAL "win32")
    set(QRCode_ARCH x86)
  elseif(QRCode_WINDOWS_PLATFORM STREQUAL "arm64")
    set(QRCode_ARCH arm64)
  elseif(QRCode_WINDOWS_PLATFORM STREQUAL "x64" OR CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(QRCode_ARCH x64)
  else()
    set(QRCode_ARCH x86)
  endif()
elseif(APPLE)
  set(QRCode_PLATFORM macos)
  set(QRCode_ARCH "${CMAKE_OSX_ARCHITECTURES}")
elseif(UNIX AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(QRCode_PLATFORM linux)
  set(QRCode_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
else()
  message(FATAL_ERROR "Unsupported qrcode target ${CMAKE_SYSTEM_NAME}/${CMAKE_SYSTEM_PROCESSOR}")
endif()
if(NOT QRCode_ARCH)
  set(QRCode_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
endif()
list(GET QRCode_ARCH 0 QRCode_ARCH)
if(QRCode_ARCH STREQUAL "amd64")
  set(QRCode_ARCH x86_64)
elseif(QRCode_ARCH STREQUAL "aarch64" AND NOT QRCode_PLATFORM STREQUAL "linux")
  set(QRCode_ARCH arm64)
elseif(QRCode_ARCH STREQUAL "arm64" AND QRCode_PLATFORM STREQUAL "linux")
  set(QRCode_ARCH aarch64)
elseif(QRCode_ARCH STREQUAL "arm" OR QRCode_ARCH STREQUAL "armv7")
  set(QRCode_ARCH armv7l)
endif()
set(QRCODE_DIR "${QRCode_LOCAL_ROOT}/${QRCode_PLATFORM}/${QRCode_ARCH}" CACHE PATH "qrcode prebuilt directory" FORCE)
find_path(QRCODE_INCLUDE_DIR NAMES qrcode.h HINTS "${QRCODE_DIR}/include" NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
find_library(QRCODE_LIBRARY NAMES qrcode libqrcode HINTS "${QRCODE_DIR}/lib" NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(QRCode REQUIRED_VARS QRCODE_INCLUDE_DIR QRCODE_LIBRARY)
if(QRCode_FOUND AND NOT TARGET QRCode::QRCode)
  add_library(QRCode::QRCode STATIC IMPORTED)
  set_target_properties(QRCode::QRCode PROPERTIES IMPORTED_LOCATION "${QRCODE_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${QRCODE_INCLUDE_DIR}")
endif()
