# SPDX-FileCopyrightText: 2026 Amalgam Solucoes em TI Ltda.
# SPDX-License-Identifier: MIT
name: Build qrcode static libraries

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths: [qrcode/**, .github/workflows/build-qrcode.yml, .github/workflows/build-qrcode-common.yml]

jobs:
  build:
    uses: ./.github/workflows/build-qrcode-common.yml
    with:
      dependency: qrcode
      library: qrcode
      build_windows: false
