# SPDX-FileCopyrightText: 2026 Amalgam Solucoes em TI Ltda.
# SPDX-License-Identifier: MIT
name: Build qrcodegen static libraries

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths: [qrcodegen/**, .github/actions/build-native-library/action.yml, .github/workflows/build-qrcodegen.yml, .github/workflows/build-qrcode-common.yml, .github/scripts/verify-windows-static-runtime.ps1]

jobs:
  build:
    uses: ./.github/workflows/build-qrcode-common.yml
    with:
      dependency: qrcodegen
      library: qrcodegen
      build_windows: true
